# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Geodatabase2Geopackage
                                 A QGIS plugin
 Copy all feature classes from a geodatabase to an empty geopackage
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-01-26
        copyright            : (C) 2021 by Daniel Laguna Ruiz/AMAYA
        email                : daniel.laguna@juntadeandalucia.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Geodatabase2Geopackage class from file Geodatabase2Geopackage.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gdb2gpkg import Geodatabase2Geopackage
    return Geodatabase2Geopackage(iface)
